version: '3.3'

services:
   db:
     container_name: mysql
     image: mysql
     volumes:
       - wp_db:/var/lib/mysql/
    
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     networks:
     - wp

   wordpress:
     depends_on:
       - db
     container_name: wordpress
     image: wordpress:latest
     volumes:
       - wp_statics:/var/www/html/
     ports:
       - 8000:80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     networks:
     - wp
   phpmyadmin:
     depends_on:
       - db
      
     image: phpmyadmin/phpmyadmin
     
     ports:
      - 7777:80
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: root 
    
     networks:
     - wp



networks:
  wp:

volumes:
  wp_db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /VOLUMES/db
  wp_statics:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /VOLUMES/web

